### ISSUE TITLE
Closes after help/intro output

### ISSUE THREAD

**Issue by DenisVCode** [abehaskins/firepit#10]
Hi, after it downloaded npm packages it just closed. After opening again, it closes instantly. For a brief window, I can see probably output of help command or some introduction. 

I tried deleting .cache firebase folder and running it with admin rights. Same result. 

Firebase folder contains bin and cli folders.
Content of npmrc is prefix = C:\Users\denis\.cache\firebase\cli

**Comment by abeisgoat** [comment]
Working on it now :) looks like a regression introduced between 0.0.6 and 0.0.8

**Comment by abeisgoat** [comment]
Should be fixed in `0.0.9` :D
