### ISSUE TITLE
Using Ctrl+C closes .exe

### ISSUE THREAD

**Issue by jamesxv7** [abehaskins/firepit#5]
I don't know if it is by design but using Ctrl+C close the whole .exe when the expected is to stop the script being executed. For example, when running `firebase serve` to test some simple web and then, lets says, I would like to stop the execution of the serve script, I can't do it using Ctrl+C.

**Comment by abeisgoat** [comment]
I noticed this too, but thought I was just being dumb. It's not by design. I'll look into why it's happening.

**Comment by abeisgoat** [comment]
(Whoops, accidental close)

This is probably related to improper signal handling (probably [SIGINT](https://nodejs.org/api/process.html#process_signal_events)) by the top-level firepit instance. It should probably reject `CTRL-C` entirely and prompt the user to run an exit command to leave the firebase shell.

**Comment by abeisgoat** [comment]
Should be all good in 0.0.6, feel free to re-open if you're still seeing this.
